package com.mooncell07.cecc.core

data class Instruction(
    val instructionType: InstructionType,
    val addressingMode: AddressingMode,
    val registerType: RegisterType,
    val flagType: FlagType,
)

val instructionTable: Array<Instruction> = Array(256) {
    Instruction(InstructionType.NONE, AddressingMode.NONE, RegisterType.NONE, FlagType.NONE)
}

fun buildInstructionTable() {
    instructionTable[0x00] = Instruction(InstructionType.BRK, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.NONE)
    instructionTable[0x01] = Instruction(InstructionType.ORA, AddressingMode.X_INDIRECT, RegisterType.A, FlagType.NONE)
    instructionTable[0x05] = Instruction(InstructionType.ORA, AddressingMode.ZEROPAGE, RegisterType.A, FlagType.NONE)
    instructionTable[0x06] = Instruction(InstructionType.ASL, AddressingMode.ZEROPAGE, RegisterType.NONE, FlagType.C)
    instructionTable[0x08] = Instruction(InstructionType.PUSH, AddressingMode.IMPLIED, RegisterType.SR, FlagType.NONE)
    instructionTable[0x09] = Instruction(InstructionType.ORA, AddressingMode.IMMEDIATE, RegisterType.A, FlagType.NONE)
    instructionTable[0x0A] = Instruction(InstructionType.ASL, AddressingMode.ACCUMULATOR, RegisterType.NONE, FlagType.C)
    instructionTable[0x0D] = Instruction(InstructionType.ORA, AddressingMode.ABSOLUTE, RegisterType.A, FlagType.NONE)
    instructionTable[0x0E] = Instruction(InstructionType.ASL, AddressingMode.ABSOLUTE, RegisterType.NONE, FlagType.C)

    instructionTable[0x10] = Instruction(InstructionType.BRCLR, AddressingMode.RELATIVE, RegisterType.NONE, FlagType.N)
    instructionTable[0x11] = Instruction(InstructionType.ORA, AddressingMode.INDIRECT_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0x15] = Instruction(InstructionType.ORA, AddressingMode.ZEROPAGE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0x16] = Instruction(InstructionType.ASL, AddressingMode.ZEROPAGE_X, RegisterType.NONE, FlagType.C)
    instructionTable[0x18] = Instruction(InstructionType.CLEAR, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.C)
    instructionTable[0x19] = Instruction(InstructionType.ORA, AddressingMode.ABSOLUTE_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0x1D] = Instruction(InstructionType.ORA, AddressingMode.ABSOLUTE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0x1E] = Instruction(InstructionType.ASL, AddressingMode.ABSOLUTE_X, RegisterType.NONE, FlagType.C)

    instructionTable[0x20] = Instruction(InstructionType.JSR, AddressingMode.ABSOLUTE, RegisterType.NONE, FlagType.NONE)
    instructionTable[0x21] = Instruction(InstructionType.AND, AddressingMode.X_INDIRECT, RegisterType.A, FlagType.NONE)
    instructionTable[0x24] = Instruction(InstructionType.BIT, AddressingMode.ZEROPAGE, RegisterType.SR, FlagType.NONE)
    instructionTable[0x25] = Instruction(InstructionType.AND, AddressingMode.ZEROPAGE, RegisterType.A, FlagType.NONE)
    instructionTable[0x26] = Instruction(InstructionType.ROL, AddressingMode.ZEROPAGE, RegisterType.NONE, FlagType.C)
    instructionTable[0x28] = Instruction(InstructionType.PULL, AddressingMode.IMPLIED, RegisterType.SR, FlagType.NONE)
    instructionTable[0x29] = Instruction(InstructionType.AND, AddressingMode.IMMEDIATE, RegisterType.A, FlagType.NONE)
    instructionTable[0x2A] = Instruction(InstructionType.ROL, AddressingMode.ACCUMULATOR, RegisterType.NONE, FlagType.C)
    instructionTable[0x2C] = Instruction(InstructionType.BIT, AddressingMode.ABSOLUTE, RegisterType.SR, FlagType.NONE)
    instructionTable[0x2D] = Instruction(InstructionType.AND, AddressingMode.ABSOLUTE, RegisterType.A, FlagType.NONE)
    instructionTable[0x2E] = Instruction(InstructionType.ROL, AddressingMode.ABSOLUTE, RegisterType.NONE, FlagType.C)

    instructionTable[0x30] = Instruction(InstructionType.BRSET, AddressingMode.RELATIVE, RegisterType.NONE, FlagType.N)
    instructionTable[0x31] = Instruction(InstructionType.AND, AddressingMode.INDIRECT_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0x35] = Instruction(InstructionType.AND, AddressingMode.ZEROPAGE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0x36] = Instruction(InstructionType.ROL, AddressingMode.ZEROPAGE_X, RegisterType.NONE, FlagType.C)
    instructionTable[0x38] = Instruction(InstructionType.SET, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.C)
    instructionTable[0x39] = Instruction(InstructionType.AND, AddressingMode.ABSOLUTE_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0x3D] = Instruction(InstructionType.AND, AddressingMode.ABSOLUTE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0x3E] = Instruction(InstructionType.ROL, AddressingMode.ABSOLUTE_X, RegisterType.NONE, FlagType.C)

    instructionTable[0x40] = Instruction(InstructionType.RTI, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.NONE)
    instructionTable[0x41] = Instruction(InstructionType.EOR, AddressingMode.X_INDIRECT, RegisterType.A, FlagType.NONE)
    instructionTable[0x45] = Instruction(InstructionType.EOR, AddressingMode.ZEROPAGE, RegisterType.A, FlagType.NONE)
    instructionTable[0x46] = Instruction(InstructionType.LSR, AddressingMode.ZEROPAGE, RegisterType.NONE, FlagType.C)
    instructionTable[0x48] = Instruction(InstructionType.PUSH, AddressingMode.IMPLIED, RegisterType.A, FlagType.NONE)
    instructionTable[0x49] = Instruction(InstructionType.EOR, AddressingMode.IMMEDIATE, RegisterType.A, FlagType.NONE)
    instructionTable[0x4A] = Instruction(InstructionType.LSR, AddressingMode.ACCUMULATOR, RegisterType.NONE, FlagType.C)
    instructionTable[0x4C] = Instruction(InstructionType.JMP, AddressingMode.ABSOLUTE, RegisterType.NONE, FlagType.NONE)
    instructionTable[0x4D] = Instruction(InstructionType.EOR, AddressingMode.ABSOLUTE, RegisterType.A, FlagType.NONE)
    instructionTable[0x4E] = Instruction(InstructionType.LSR, AddressingMode.ABSOLUTE, RegisterType.NONE, FlagType.C)

    instructionTable[0x50] = Instruction(InstructionType.BRCLR, AddressingMode.RELATIVE, RegisterType.NONE, FlagType.V)
    instructionTable[0x51] = Instruction(InstructionType.EOR, AddressingMode.INDIRECT_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0x55] = Instruction(InstructionType.EOR, AddressingMode.ZEROPAGE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0x56] = Instruction(InstructionType.LSR, AddressingMode.ZEROPAGE_X, RegisterType.NONE, FlagType.C)
    instructionTable[0x58] = Instruction(InstructionType.CLEAR, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.I)
    instructionTable[0x59] = Instruction(InstructionType.EOR, AddressingMode.ABSOLUTE_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0x5D] = Instruction(InstructionType.EOR, AddressingMode.ABSOLUTE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0x5E] = Instruction(InstructionType.LSR, AddressingMode.ABSOLUTE_X, RegisterType.NONE, FlagType.C)

    instructionTable[0x60] = Instruction(InstructionType.RTS, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.NONE)
    instructionTable[0x61] = Instruction(InstructionType.ADC, AddressingMode.X_INDIRECT, RegisterType.A, FlagType.C)
    instructionTable[0x65] = Instruction(InstructionType.ADC, AddressingMode.ZEROPAGE, RegisterType.A, FlagType.C)
    instructionTable[0x66] = Instruction(InstructionType.ROR, AddressingMode.ZEROPAGE, RegisterType.NONE, FlagType.C)
    instructionTable[0x68] = Instruction(InstructionType.PULL, AddressingMode.IMPLIED, RegisterType.A, FlagType.NONE)
    instructionTable[0x69] = Instruction(InstructionType.ADC, AddressingMode.IMMEDIATE, RegisterType.A, FlagType.C)
    instructionTable[0x6A] = Instruction(InstructionType.ROR, AddressingMode.ACCUMULATOR, RegisterType.NONE, FlagType.C)
    instructionTable[0x6C] = Instruction(InstructionType.JMP, AddressingMode.INDIRECT, RegisterType.NONE, FlagType.NONE)
    instructionTable[0x6D] = Instruction(InstructionType.ADC, AddressingMode.ABSOLUTE, RegisterType.A, FlagType.C)
    instructionTable[0x6E] = Instruction(InstructionType.ROR, AddressingMode.ABSOLUTE, RegisterType.NONE, FlagType.C)

    instructionTable[0x70] = Instruction(InstructionType.BRSET, AddressingMode.RELATIVE, RegisterType.NONE, FlagType.V)
    instructionTable[0x71] = Instruction(InstructionType.ADC, AddressingMode.INDIRECT_Y, RegisterType.A, FlagType.C)
    instructionTable[0x75] = Instruction(InstructionType.ADC, AddressingMode.ZEROPAGE_X, RegisterType.A, FlagType.C)
    instructionTable[0x76] = Instruction(InstructionType.ROR, AddressingMode.ZEROPAGE_X, RegisterType.NONE, FlagType.C)
    instructionTable[0x78] = Instruction(InstructionType.SET, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.I)
    instructionTable[0x79] = Instruction(InstructionType.ADC, AddressingMode.ABSOLUTE_Y, RegisterType.A, FlagType.C)
    instructionTable[0x7D] = Instruction(InstructionType.ADC, AddressingMode.ABSOLUTE_X, RegisterType.A, FlagType.C)
    instructionTable[0x7E] = Instruction(InstructionType.ROR, AddressingMode.ABSOLUTE_X, RegisterType.NONE, FlagType.C)

    instructionTable[0x81] = Instruction(InstructionType.STORE, AddressingMode.X_INDIRECT, RegisterType.A, FlagType.NONE)
    instructionTable[0x84] = Instruction(InstructionType.STORE, AddressingMode.ZEROPAGE, RegisterType.Y, FlagType.NONE)
    instructionTable[0x85] = Instruction(InstructionType.STORE, AddressingMode.ZEROPAGE, RegisterType.A, FlagType.NONE)
    instructionTable[0x86] = Instruction(InstructionType.STORE, AddressingMode.ZEROPAGE, RegisterType.X, FlagType.NONE)
    instructionTable[0x88] = Instruction(InstructionType.DECREMENT, AddressingMode.IMPLIED, RegisterType.Y, FlagType.NONE)
    instructionTable[0x8A] = Instruction(InstructionType.TXA, AddressingMode.IMPLIED, RegisterType.A, FlagType.NONE)
    instructionTable[0x8C] = Instruction(InstructionType.STORE, AddressingMode.ABSOLUTE, RegisterType.Y, FlagType.NONE)
    instructionTable[0x8D] = Instruction(InstructionType.STORE, AddressingMode.ABSOLUTE, RegisterType.A, FlagType.NONE)
    instructionTable[0x8E] = Instruction(InstructionType.STORE, AddressingMode.ABSOLUTE, RegisterType.X, FlagType.NONE)

    instructionTable[0x90] = Instruction(InstructionType.BRCLR, AddressingMode.RELATIVE, RegisterType.NONE, FlagType.C)
    instructionTable[0x91] = Instruction(InstructionType.STORE, AddressingMode.INDIRECT_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0x94] = Instruction(InstructionType.STORE, AddressingMode.ZEROPAGE_X, RegisterType.Y, FlagType.NONE)
    instructionTable[0x95] = Instruction(InstructionType.STORE, AddressingMode.ZEROPAGE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0x96] = Instruction(InstructionType.STORE, AddressingMode.ZEROPAGE_Y, RegisterType.X, FlagType.NONE)
    instructionTable[0x98] = Instruction(InstructionType.TYA, AddressingMode.IMPLIED, RegisterType.A, FlagType.NONE)
    instructionTable[0x99] = Instruction(InstructionType.STORE, AddressingMode.ABSOLUTE_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0x9A] = Instruction(InstructionType.TXS, AddressingMode.IMPLIED, RegisterType.SP, FlagType.NONE)
    instructionTable[0x9D] = Instruction(InstructionType.STORE, AddressingMode.ABSOLUTE_X, RegisterType.A, FlagType.NONE)

    instructionTable[0xA0] = Instruction(InstructionType.LOAD, AddressingMode.IMMEDIATE, RegisterType.Y, FlagType.NONE)
    instructionTable[0xA1] = Instruction(InstructionType.LOAD, AddressingMode.X_INDIRECT, RegisterType.A, FlagType.NONE)
    instructionTable[0xA2] = Instruction(InstructionType.LOAD, AddressingMode.IMMEDIATE, RegisterType.X, FlagType.NONE)
    instructionTable[0xA4] = Instruction(InstructionType.LOAD, AddressingMode.ZEROPAGE, RegisterType.Y, FlagType.NONE)
    instructionTable[0xA5] = Instruction(InstructionType.LOAD, AddressingMode.ZEROPAGE, RegisterType.A, FlagType.NONE)
    instructionTable[0xA6] = Instruction(InstructionType.LOAD, AddressingMode.ZEROPAGE, RegisterType.X, FlagType.NONE)
    instructionTable[0xA8] = Instruction(InstructionType.TAY, AddressingMode.IMPLIED, RegisterType.Y, FlagType.NONE)
    instructionTable[0xA9] = Instruction(InstructionType.LOAD, AddressingMode.IMMEDIATE, RegisterType.A, FlagType.NONE)
    instructionTable[0xAA] = Instruction(InstructionType.TAX, AddressingMode.IMPLIED, RegisterType.X, FlagType.NONE)
    instructionTable[0xAC] = Instruction(InstructionType.LOAD, AddressingMode.ABSOLUTE, RegisterType.Y, FlagType.NONE)
    instructionTable[0xAD] = Instruction(InstructionType.LOAD, AddressingMode.ABSOLUTE, RegisterType.A, FlagType.NONE)
    instructionTable[0xAE] = Instruction(InstructionType.LOAD, AddressingMode.ABSOLUTE, RegisterType.X, FlagType.NONE)

    instructionTable[0xB0] = Instruction(InstructionType.BRSET, AddressingMode.RELATIVE, RegisterType.NONE, FlagType.C)
    instructionTable[0xB1] = Instruction(InstructionType.LOAD, AddressingMode.INDIRECT_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0xB4] = Instruction(InstructionType.LOAD, AddressingMode.ZEROPAGE_X, RegisterType.Y, FlagType.NONE)
    instructionTable[0xB5] = Instruction(InstructionType.LOAD, AddressingMode.ZEROPAGE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0xB6] = Instruction(InstructionType.LOAD, AddressingMode.ZEROPAGE_Y, RegisterType.X, FlagType.NONE)
    instructionTable[0xB8] = Instruction(InstructionType.CLEAR, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.V)
    instructionTable[0xB9] = Instruction(InstructionType.LOAD, AddressingMode.ABSOLUTE_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0xBA] = Instruction(InstructionType.TSX, AddressingMode.IMPLIED, RegisterType.X, FlagType.NONE)
    instructionTable[0xBC] = Instruction(InstructionType.LOAD, AddressingMode.ABSOLUTE_X, RegisterType.Y, FlagType.NONE)
    instructionTable[0xBD] = Instruction(InstructionType.LOAD, AddressingMode.ABSOLUTE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0xBE] = Instruction(InstructionType.LOAD, AddressingMode.ABSOLUTE_Y, RegisterType.X, FlagType.NONE)

    instructionTable[0xC0] = Instruction(InstructionType.COMPARE, AddressingMode.IMMEDIATE, RegisterType.Y, FlagType.NONE)
    instructionTable[0xC1] = Instruction(InstructionType.COMPARE, AddressingMode.X_INDIRECT, RegisterType.A, FlagType.NONE)
    instructionTable[0xC4] = Instruction(InstructionType.COMPARE, AddressingMode.ZEROPAGE, RegisterType.Y, FlagType.NONE)
    instructionTable[0xC5] = Instruction(InstructionType.COMPARE, AddressingMode.ZEROPAGE, RegisterType.A, FlagType.NONE)
    instructionTable[0xC6] = Instruction(InstructionType.DECREMENT, AddressingMode.ZEROPAGE, RegisterType.NONE, FlagType.NONE)
    instructionTable[0xC8] = Instruction(InstructionType.INCREMENT, AddressingMode.IMPLIED, RegisterType.Y, FlagType.NONE)
    instructionTable[0xC9] = Instruction(InstructionType.COMPARE, AddressingMode.IMMEDIATE, RegisterType.A, FlagType.NONE)
    instructionTable[0xCA] = Instruction(InstructionType.DECREMENT, AddressingMode.IMPLIED, RegisterType.X, FlagType.NONE)
    instructionTable[0xCC] = Instruction(InstructionType.COMPARE, AddressingMode.ABSOLUTE, RegisterType.Y, FlagType.NONE)
    instructionTable[0xCD] = Instruction(InstructionType.COMPARE, AddressingMode.ABSOLUTE, RegisterType.A, FlagType.NONE)
    instructionTable[0xCE] = Instruction(InstructionType.DECREMENT, AddressingMode.ABSOLUTE, RegisterType.NONE, FlagType.NONE)

    instructionTable[0xD0] = Instruction(InstructionType.BRCLR, AddressingMode.RELATIVE, RegisterType.NONE, FlagType.Z)
    instructionTable[0xD1] = Instruction(InstructionType.COMPARE, AddressingMode.INDIRECT_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0xD5] = Instruction(InstructionType.COMPARE, AddressingMode.ZEROPAGE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0xD6] = Instruction(InstructionType.DECREMENT, AddressingMode.ZEROPAGE_X, RegisterType.NONE, FlagType.NONE)
    instructionTable[0xD8] = Instruction(InstructionType.CLEAR, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.D)
    instructionTable[0xD9] = Instruction(InstructionType.COMPARE, AddressingMode.ABSOLUTE_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0xDD] = Instruction(InstructionType.COMPARE, AddressingMode.ABSOLUTE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0xDE] = Instruction(InstructionType.DECREMENT, AddressingMode.ABSOLUTE_X, RegisterType.NONE, FlagType.NONE)

    instructionTable[0xE0] = Instruction(InstructionType.COMPARE, AddressingMode.IMMEDIATE, RegisterType.X, FlagType.NONE)
    instructionTable[0xE1] = Instruction(InstructionType.SBC, AddressingMode.X_INDIRECT, RegisterType.A, FlagType.NONE)
    instructionTable[0xE4] = Instruction(InstructionType.COMPARE, AddressingMode.ZEROPAGE, RegisterType.X, FlagType.NONE)
    instructionTable[0xE5] = Instruction(InstructionType.SBC, AddressingMode.ZEROPAGE, RegisterType.A, FlagType.NONE)
    instructionTable[0xE6] = Instruction(InstructionType.INCREMENT, AddressingMode.ZEROPAGE, RegisterType.NONE, FlagType.NONE)
    instructionTable[0xE8] = Instruction(InstructionType.INCREMENT, AddressingMode.IMPLIED, RegisterType.X, FlagType.NONE)
    instructionTable[0xE9] = Instruction(InstructionType.SBC, AddressingMode.IMMEDIATE, RegisterType.A, FlagType.NONE)
    instructionTable[0xEA] = Instruction(InstructionType.NOP, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.NONE)
    instructionTable[0xEC] = Instruction(InstructionType.COMPARE, AddressingMode.ABSOLUTE, RegisterType.X, FlagType.NONE)
    instructionTable[0xED] = Instruction(InstructionType.SBC, AddressingMode.ABSOLUTE, RegisterType.A, FlagType.NONE)
    instructionTable[0xEE] = Instruction(InstructionType.INCREMENT, AddressingMode.ABSOLUTE, RegisterType.X, FlagType.NONE)

    instructionTable[0xF0] = Instruction(InstructionType.BRSET, AddressingMode.RELATIVE, RegisterType.NONE, FlagType.Z)
    instructionTable[0xF1] = Instruction(InstructionType.SBC, AddressingMode.INDIRECT_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0xF5] = Instruction(InstructionType.SBC, AddressingMode.ZEROPAGE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0xF6] = Instruction(InstructionType.INCREMENT, AddressingMode.ZEROPAGE_X, RegisterType.NONE, FlagType.NONE)
    instructionTable[0xF8] = Instruction(InstructionType.SET, AddressingMode.IMPLIED, RegisterType.NONE, FlagType.D)
    instructionTable[0xF9] = Instruction(InstructionType.SBC, AddressingMode.ABSOLUTE_Y, RegisterType.A, FlagType.NONE)
    instructionTable[0xFD] = Instruction(InstructionType.SBC, AddressingMode.ABSOLUTE_X, RegisterType.A, FlagType.NONE)
    instructionTable[0xFE] = Instruction(InstructionType.INCREMENT, AddressingMode.ABSOLUTE_X, RegisterType.NONE, FlagType.NONE)
}
