package com.mooncell07.cecc.core

data class INSTR(
    val insType: IT,
    val addrMode: AM,
    val regType: RT,
    val flagType: FT,
)

val INSTAB: Array<INSTR?> = arrayOfNulls(256)

fun buildInstructionTable() {
    INSTAB[0x00] = INSTR(IT.BRK, AM.IMPLIED, RT.NONE, FT.NONE)
    INSTAB[0x01] = INSTR(IT.ORQ, AM.X_INDIRECT, RT.A, FT.NONE)
    INSTAB[0x05] = INSTR(IT.ORQ, AM.ZEROPAGE, RT.A, FT.NONE)
    INSTAB[0x06] = INSTR(IT.ASL, AM.ZEROPAGE, RT.NONE, FT.C)
    INSTAB[0x08] = INSTR(IT.PHQ, AM.IMPLIED, RT.SR, FT.NONE)
    INSTAB[0x09] = INSTR(IT.ORQ, AM.IMMEDIATE, RT.A, FT.NONE)
    INSTAB[0x0A] = INSTR(IT.ASL, AM.ZEROPAGE, RT.NONE, FT.C)
    INSTAB[0x0D] = INSTR(IT.ORQ, AM.ABSOLUTE, RT.A, FT.NONE)
    INSTAB[0x0E] = INSTR(IT.ASL, AM.ABSOLUTE, RT.NONE, FT.C)

    INSTAB[0x10] = INSTR(IT.BPL, AM.RELATIVE, RT.NONE, FT.N)
    INSTAB[0x11] = INSTR(IT.ORQ, AM.INDIRECT_Y, RT.A, FT.NONE)
    INSTAB[0x15] = INSTR(IT.ORQ, AM.ZEROPAGE_X, RT.A, FT.NONE)
    INSTAB[0x16] = INSTR(IT.ASL, AM.ZEROPAGE_X, RT.NONE, FT.C)
    INSTAB[0x18] = INSTR(IT.CLQ, AM.IMPLIED, RT.NONE, FT.C)
    INSTAB[0x19] = INSTR(IT.ORQ, AM.ABSOLUTE_Y, RT.A, FT.NONE)
    INSTAB[0x1D] = INSTR(IT.ORQ, AM.ABSOLUTE_X, RT.A, FT.NONE)
    INSTAB[0x1E] = INSTR(IT.ASL, AM.ABSOLUTE_X, RT.NONE, FT.C)

    INSTAB[0x20] = INSTR(IT.JSR, AM.ABSOLUTE, RT.NONE, FT.NONE)
    INSTAB[0x21] = INSTR(IT.AND, AM.X_INDIRECT, RT.A, FT.NONE)
    INSTAB[0x24] = INSTR(IT.BIT, AM.ZEROPAGE, RT.SR, FT.NONE)
    INSTAB[0x25] = INSTR(IT.AND, AM.ZEROPAGE, RT.A, FT.NONE)
    INSTAB[0x26] = INSTR(IT.ROL, AM.ZEROPAGE, RT.NONE, FT.C)
    INSTAB[0x28] = INSTR(IT.PLQ, AM.IMPLIED, RT.SR, FT.NONE)
    INSTAB[0x29] = INSTR(IT.AND, AM.IMMEDIATE, RT.A, FT.NONE)
    INSTAB[0x2A] = INSTR(IT.ROL, AM.ACCUMULATOR, RT.NONE, FT.C)
    INSTAB[0x2C] = INSTR(IT.BIT, AM.ABSOLUTE, RT.SR, FT.NONE)
    INSTAB[0x2D] = INSTR(IT.AND, AM.ABSOLUTE, RT.A, FT.NONE)
    INSTAB[0x2E] = INSTR(IT.ROL, AM.ABSOLUTE, RT.NONE, FT.C)

    INSTAB[0x30] = INSTR(IT.BRQ, AM.RELATIVE, RT.NONE, FT.N)
    INSTAB[0x31] = INSTR(IT.AND, AM.INDIRECT_Y, RT.A, FT.NONE)
    INSTAB[0x35] = INSTR(IT.AND, AM.ZEROPAGE_X, RT.A, FT.NONE)
    INSTAB[0x36] = INSTR(IT.ROL, AM.ZEROPAGE_X, RT.NONE, FT.C)
    INSTAB[0x38] = INSTR(IT.SEQ, AM.IMPLIED, RT.NONE, FT.C)
    INSTAB[0x39] = INSTR(IT.AND, AM.ABSOLUTE_Y, RT.A, FT.NONE)
    INSTAB[0x3D] = INSTR(IT.AND, AM.ABSOLUTE_X, RT.A, FT.NONE)
    INSTAB[0x3E] = INSTR(IT.ROL, AM.ABSOLUTE_X, RT.NONE, FT.C)
}
